id: PC4C364F7
initial_creation_type: ocr
source_metadata:
  volumes:
    6d4c37c5c2994bee8a4419564a10edbc:
      base_file: v046.txt
      image_group_id: I1PD95891
      title: ''
      total_pages: 1201
      volume_number: 46
